### PR TITLE
Add dynamic module support

### LINKED ISSUE #41: Dynamic loadable support
Hello if you have some time would it be possible to add support for loading this great module as a dynamic module as is supported in the new nginx 1.9.11?

https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/
https://www.nginx.com/resources/wiki/extending/converting/

### PR DESCRIPTION
**Pull request by davidjb**
Resolves #41 and makes #31 solvable by using `pkg-oss` for nginx (details at https://www.nginx.com/blog/creating-installable-packages-dynamic-modules/)

### CODE REVIEW

**Comment by davidjb** [comment]
@yaoweibin Any chance this PR could be merged?  I've been using this code in my builds for a long while without issues.

**Comment by jsoref** [comment]
@yaoweibin, should developers/users switch to using a different fork?

https://github.com/yaoweibin/nginx_ajp_module/network shows 3 forks w/ this PR merged.
https://github.com/vozlt/nginx_ajp_module/commit/3b41fcc14381ec167bc610d33c8fdeed24734701 shows an **nginx** 1.7.9+ thing
https://github.com/sklochkov/nginx_ajp_module/commit/960a5dc5d9999f117c3769faac9d89b272ca7ca7 maintains handling for `SCRIPT_URL`

**Comment by davidjb** [comment]
@yaoweibin Ping - just checking in again if this PR can be merged.  Thanks!

**Comment by yaoweibin** [comment]
OK,  Are you still use the ajp module for Java?

**Pull request merged**
